### ISSUE TITLE
Client Secret shouldn't be exposed

### ISSUE THREAD

**Issue by matuella** [dotronglong/dart-github-sign-in#11]
As per Github's official [docs](https://docs.github.com/en/rest/guides/basics-of-authentication#registering-your-app):

> ... Every registered OAuth application is assigned a unique Client ID and Client Secret. **The Client Secret should not be shared**! That includes checking the string into your repository.

So I guess the current solution is exposing a crucial (sensitive) information that shouldn't be available in the client. Am I missing something here?

**Comment by dotronglong** [comment]
Hi @matuella . First and foremost, thank you for your question. This package is only exposed client id which it makes sense. Regarding client secret, it is only used to exchange the token, hence, it is secure by default using HTTPS connection to Github. Hope it helps. Thank you.

================
Out of the book, there are some cases the secret can be exploded:
- If someone can hijack the secure connection between client and Github
- Or they can download the app from Apple (or Google) and crack their system to decode the app.

However, it only allows them to see the secret, but cannot access to the data more than the app is allowed. Hence, it is always a best choice to limit the scopes of the app to least information as possible.

**Comment by ggirotto** [comment]
> However, it only allows them to see the secret, but cannot access to the data more than the app is allowed.

Ok, they can't, but exposing the secret in the client just cut-off this security layer. It's the same as not having the secret, because it's exposed. We should follow the principle that everything that is in the client is public, since anyone can access it with a given effort.

TLDR: Exposing the secret is the same as not using this security layer, thus, doesn't make sense and can be exploited by someone.

As a comparison - a little more exaggerated I would say - is like exposing the Recaptcha Private Key in the client. We are taking out this security layer of the whole OAuth process.
